language: java
jdk:
  - openjdk15

before_install:
  - chmod +x ./mvnw

branches:
  only:
    - dev-v1

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2'

script: "mvn clean install"

notifications:
  email:
    recipients:
      - sftth@naver.com